/*
 * generated by Xtext
 */
package org.ffenn;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VrmlRuntimeModule extends org.ffenn.AbstractVrmlRuntimeModule {

}
