/*
* generated by Xtext
*/
package org.ffenn.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class VrmlTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
