/*
* generated by Xtext
*/
package org.ffenn.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;
import org.ffenn.vrml.DefStatement;
import org.ffenn.vrml.Node;
import org.ffenn.vrml.Proto;
import org.ffenn.vrml.Script;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class VrmlLabelProvider extends DefaultLabelProvider {
	
	String text(Node el) {
		return el.getName();
	}
	
	String text(DefStatement el) {
		String text = "DEF " + el.getName();
		if (el.getNode() instanceof Script) {
			text += " [Script]";
		} else if (el.getNode() instanceof Node) {
			text += " [" + ((Node)el.getNode()).getName() + "]";
		}
		return text;
	}
	
	String text(Proto el) {
		return "PROTO " + el.getName();
	}
}
