/*
 * generated by Xtext
 */
package org.ffenn;

import org.ffenn.syntaxcoloring.VrmlSemanticHighlightingCalculator;
import org.ffenn.syntaxcoloring.VrmlSemanticHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VrmlUiModule extends org.ffenn.AbstractVrmlUiModule {
	public Class<? extends org.eclipse.xtext.ui.common.editor.syntaxcoloring.ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return VrmlSemanticHighlightingCalculator.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.common.editor.syntaxcoloring.ISemanticHighlightingConfiguration> bindSemanticHighlightingConfiguration() {
		return VrmlSemanticHighlightingConfiguration.class;
	}
}
